apiVersion: v1
kind: ConfigMap
metadata:
  name: sp-infra
  namespace: silentpulse
data:
  WORKER_IMAGE: "silentpulse-worker:latest"
  SCHEDULER_IMAGE: "silentpulse-scheduler:latest"
  REDIS_ADDR: "silentpulse-redis:6379"
  IMAGE_PULL_POLICY: "IfNotPresent"
  POSTGRES_HOST: "silentpulse-postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "silentpulse"
  POSTGRES_USER: "silentpulse"
