apiVersion: v1
kind: Secret
metadata:
  name: sp-secrets
  namespace: silentpulse
type: Opaque
stringData:
  POSTGRES_PASSWORD: "silentpulse"
  POSTGRES_DSN: "postgres://silentpulse:silentpulse@silentpulse-postgres:5432/silentpulse?sslmode=disable"
  ENCRYPTION_KEY: ""
