apiVersion: apps/v1
kind: Deployment
metadata:
  name: silentpulse-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: silentpulse-frontend
    {{- include "silentpulse.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: silentpulse-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: silentpulse-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.frontend.port | quote }}
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: NEXT_PUBLIC_API_URL
              value: {{ .Values.frontend.apiUrl | quote }}
          livenessProbe:
            httpGet:
              path: /ui
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ui
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
