apiVersion: apps/v1
kind: Deployment
metadata:
  name: silentpulse-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: silentpulse-api
    {{- include "silentpulse.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: silentpulse-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: silentpulse-api
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.api.port | quote }}
          envFrom:
            - configMapRef:
                name: silentpulse-config
            - secretRef:
                name: silentpulse-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
