apiVersion: v1
kind: Secret
metadata:
  name: silentpulse-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "silentpulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  JWT_SECRET: {{ .Values.auth.jwtSecret | quote }}
  ENCRYPTION_KEY: {{ .Values.auth.encryptionKey | quote }}
  POSTGRES_DSN: {{ include "silentpulse.postgresDSN" . | quote }}
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  {{- end }}
  {{- if .Values.auth.healthAPIKey }}
  HEALTH_API_KEY: {{ .Values.auth.healthAPIKey | quote }}
  {{- end }}
  {{- if .Values.license.key }}
  SILENTPULSE_LICENSE_KEY: {{ .Values.license.key | quote }}
  {{- end }}
