apiVersion: v1
kind: Service
metadata:
  name: silentpulse-cmdb-sync
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: silentpulse-cmdb-sync
    {{- include "silentpulse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cmdbSync.port }}
      targetPort: {{ .Values.cmdbSync.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: silentpulse-cmdb-sync
