apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: silentpulse-operator
subjects:
  - kind: ServiceAccount
    name: silentpulse-operator
    namespace: silentpulse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: silentpulse-operator
