{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: silentpulse-postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: silentpulse-postgres
    {{- include "silentpulse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: silentpulse-postgres
{{- end }}
