apiVersion: v1
kind: Service
metadata:
  name: silentpulse-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: silentpulse-redis
    {{- include "silentpulse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: silentpulse-redis
