apiVersion: v1
kind: ServiceAccount
metadata:
  name: silentpulse-operator
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: silentpulse-operator
    {{- include "silentpulse.labels" . | nindent 4 }}
